=== DavidWhitlock/PortlandStateJava/src/edu/pdx/cs399J/family/familytree.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!-- DTD for describing a family tree, people, and marriages -->

<!-- A family tree consists of some number of people and some number
     of marriages -->
<!ELEMENT familytree (person*, marriage*)>

<!-- A person consists of a required id and optional first, middle,
     and last name, date of birth, date of death, mother id, and 
     father id -->
<!ELEMENT person (id, firstname?, middlename?, lastname?, dob?, dod?, 
          father-id?, mother-id?)>

<!-- These guys are just text -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT middlename (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT father-id (#PCDATA)>
<!ELEMENT mother-id (#PCDATA)>

<!-- These guys are dates -->
<!ELEMENT dob (date)>
<!ELEMENT dod (date)>

<!-- Only a year is required -->
<!ELEMENT date (month?, day?, year)>

<!-- These guys are just numerical text.  Their values are determined
     by Calendar.MONTH, Calendar.DATE, and Calendar.YEAR -->
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT year (#PCDATA)>

<!-- A marriage has a husband id and wife id attributes, an optional
     date and location --> 
<!ELEMENT marriage (date?, location?)>
<!ATTLIST marriage
          husband-id  CDATA  #REQUIRED
          wife-id     CDATA  #REQUIRED
>

<!ELEMENT location (#PCDATA)>

=== DavidWhitlock/PortlandStateJava/src/edu/pdx/cs410J/familyTree/davesFamily.xml
<?xml version="1.0"?>

<!DOCTYPE familytree SYSTEM 'http://www.cs.pdx.edu/~whitlock/dtds/familytree.dtd'>

<familytree>
  <person>
    <id>7</id>
    <firstname>Doris</firstname>
    <middlename>Arlene</middlename>
    <lastname>Hartwell</lastname>
    <dob>
      <date>
	<month>7</month>
	<day>27</day>
	<year>1914</year>
      </date>
    </dob>
    <dod>
      <date>
	<month>10</month>
	<day>15</day>
	<year>2000</year>
      </date>
    </dod>
  </person>
  <person>
    <id>6</id>
    <firstname>Ralph</firstname>
    <middlename>Hawthorn</middlename>
    <lastname>Granger</lastname>
    <dob>
      <date>
	<month>5</month>
	<day>30</day>
	<year>1911</year>
      </date>
    </dob>
  </person>
  <person>
    <id>3</id>
    <firstname>Carolyn</firstname>
    <middlename>Joyce</middlename>
    <lastname>Granger</lastname>
    <dob>
      <date>
	<month>4</month>
	<day>17</day>
	<year>1945</year>
      </date>
    </dob>
    <father-id>6</father-id>
    <mother-id>7</mother-id>
  </person>
  <person>
    <id>2</id>
    <firstname>Stanley</firstname>
    <middlename>Jay</middlename>
    <lastname>Whitlock</lastname>
    <dob>
      <date>
	<month>1</month>
	<day>27</day>
	<year>1948</year>
      </date>
    </dob>
  </person>
  <person>
    <id>1</id>
    <firstname>David</firstname>
    <middlename>Michael</middlename>
    <lastname>Whitlock</lastname>
    <father-id>2</father-id>
    <mother-id>3</mother-id>
  </person>
  <marriage husband-id="2" wife-id="3">
    <date>
      <month>6</month>
      <day>12</day>
      <year>1969</year>
    </date>
    <location>Durham, NH</location>
  </marriage>
  <marriage husband-id="6" wife-id="7">
    <date>
      <month>5</month>
      <day>30</day>
      <year>1939</year>
    </date>
    <location>Worcestor, MA</location>
  </marriage>
</familytree>
